### ISSUE TITLE
is  infyom:vuejs  command  working already ? 

### ISSUE THREAD

**Issue by naysumyat** [InfyOmLabs/laravel-generator#531]
I am getting following error when I try the infyo:vuejs command.Is it work in progress or ready to use ? 

Cannot use object of type InfyOm\Generator\Common\GeneratorField as array

**Comment by datenzar** [comment]
should be solved with PR #375

**Comment by mitulgolakiya** [comment]
@naysumyat @datenzar #375 merged. Can you test it and check if it's working or not. Re-open it if problem persists.
